# Generated by Django 4.2.7 on 2023-11-16 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField()),
                ('nome', models.CharField(max_length=200)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14)),
                ('slug', models.SlugField(max_length=250)),
                ('cns', models.SlugField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=100)),
                ('sigla_setor', models.CharField(max_length=10)),
                ('cargo_responsavel_setor', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('setor_ativo', models.BooleanField(default=True)),
                ('responsavel_setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoafisica')),
                ('setor_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.setor')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ['nome_setor'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=100)),
                ('sigla_unidade', models.CharField(max_length=100)),
                ('nome_cargo_diretor', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=125)),
                ('diretor_unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoPessoaFisicaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vinculo', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('fim_vinculo', models.DateField()),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoafisica')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.setor')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoMeta4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo_ativo', models.BooleanField(default=True)),
                ('id_meta4', models.IntegerField()),
                ('id_ato_formal', models.CharField(max_length=200)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoafisica')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VinculoFuneas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo_ativo', models.BooleanField(default=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoafisica')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VinculoCnpj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo_ativo', models.BooleanField(default=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoafisica')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuns.fornecedor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='setor',
            name='unidade_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.unidade'),
        ),
        migrations.CreateModel(
            name='PessoaFisicaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoafisica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoContrachequeMeta4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lancamento', models.IntegerField()),
                ('descricao_lancamento', models.CharField(max_length=200)),
                ('valor_vantagem', models.FloatField()),
                ('valor_desconto', models.FloatField()),
                ('periodo_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuns.periodoreferencia')),
                ('vinculo_meta4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.vinculometa4')),
            ],
        ),
        migrations.CreateModel(
            name='DadosCadastraisMeta4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=200)),
                ('t_emp', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('pis', models.CharField(max_length=200)),
                ('admissao', models.DateField()),
                ('carga_horaria', models.IntegerField()),
                ('cargo', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=200)),
                ('classe', models.CharField(max_length=200)),
                ('referencia_classe', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('quadro', models.TextField(max_length=200)),
                ('id_vinculo_meta4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.vinculometa4')),
                ('periodo_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuns.periodoreferencia')),
            ],
        ),
    ]
