# Generated by Django 5.0.1 on 2024-02-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculofuncional',
            name='tipo_vinculo',
            field=models.IntegerField(choices=[(1, 'SESA'), (2, 'FUNEAS'), (3, 'CONTRATO'), (4, 'ACADEMICO')]),
        ),
    ]
