# Generated by Django 5.0.2 on 2024-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_vinculofuncional_tipo_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
