"""
Django settings for hrso_escala project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
import json

# import ldap
# from django_auth_ldap.config import LDAPSearch

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_FILE = os.path.join(BASE_DIR, 'sec.json')
OPEN_SECRET_DATA = open(SECRET_FILE)
SECRET_DATA = json.load(OPEN_SECRET_DATA)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x5bb%&34q9ge3wvd3_hg^rz3b4-=9hh86t3m)2i+bbbm-6bepa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'contratos.apps.ContratosConfig',
    'escala_geral.apps.EscalaGeralConfig',
    'pessoas.apps.PessoasConfig',
    'comuns.apps.ComunsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hrso_escala.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrso_escala.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# AUTHENTICATION_BACKENDS = [
# "django_auth_ldap.backend.LDAPBackend",
#     "django.contrib.auth.backends.ModelBackend",
# ]


DESENVOLVIMENTO = {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': os.environ.get('DB_NAME', SECRET_DATA['desenvolvimento']['DB_NAME']),
    'USER': os.environ.get('DB_USER', SECRET_DATA['desenvolvimento']['DB_USER']),
    'PASSWORD': os.environ.get('DB_PASS', SECRET_DATA['desenvolvimento']['DB_PASS']),
    'HOST': SECRET_DATA['desenvolvimento']['HOST'],
    'PORT': SECRET_DATA['desenvolvimento']['PORT'],
}

DATABASES = {
    'default': DESENVOLVIMENTO
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/accounts/login'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#
# AUTH_LDAP_CONNECTION_OPTIONS = {ldap.OPT_DEBUG_LEVEL: 1, ldap.OPT_REFERRALS: 0,}
#
# AUTH_LDAP_SERVER_URI = "ldap://10.29.126.5"
#
# AUTH_LDAP_BIND_DN = "cn=vanderlei,ou=adm_ti,dc=hrso,dc=br"
# AUTH_LDAP_BIND_PASSWORD = "seil9527"
#
# AUTH_LDAP_ALWAYS_UPDATE_USER = False
#
# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "ou=adm_ti,dc=hrso,dc=br", ldap.SCOPE_SUBTREE, "sAMAccountName=%(user)s"
# )
#
# AUTH_LDAP_START_TLS = True
#


