# Generated by Django 4.2.7 on 2023-11-16 19:30

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('comuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConselhoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala_ativa', models.BooleanField(default=True)),
                ('regime_escala', models.CharField(choices=[('P', 'presencial'), ('S', 'sobreaviso')], max_length=2)),
                ('nome_escala', models.CharField(max_length=50, verbose_name='Nome da Escala')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.setor')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
                'ordering': ['nome_escala'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('funcao_medica', models.BooleanField(default=True)),
                ('conselhos_permitidos', models.ManyToManyField(blank=True, to='escala_geral.conselhoprofissional')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cbo', models.CharField(max_length=6)),
                ('titulo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.ocupacao')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.funcao')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_plantao', models.DateField(db_index=True)),
                ('indice_plantao_escala', models.IntegerField(blank=True, null=True)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('duracao_plantao', models.DurationField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('plantao_faturado', models.BooleanField(default=False)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala_geral.profissional')),
            ],
        ),
        migrations.AddField(
            model_name='funcao',
            name='ocupacoes_permitidas',
            field=models.ManyToManyField(blank=True, to='escala_geral.ocupacao'),
        ),
        migrations.CreateModel(
            name='EscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala_ativa', models.BooleanField(default=True)),
                ('regime_escala', models.CharField(choices=[('P', 'presencial'), ('S', 'sobreaviso')], max_length=2)),
                ('nome_escala', models.CharField(max_length=50, verbose_name='Nome da Escala')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('escala_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.escala')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuns.periodoreferencia')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.setor')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
                'ordering': ['nome_escala'],
            },
        ),
        migrations.CreateModel(
            name='DadosConselhoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conselho', localflavor.br.models.BRStateField(max_length=2)),
                ('numero', models.CharField(max_length=30)),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.conselhoprofissional')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.profissional')),
            ],
        ),
    ]
