# Generated by Django 5.0.1 on 2024-01-30 16:12

import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comuns', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosConselhoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conselho', localflavor.br.models.BRStateField(max_length=2)),
                ('numero', models.CharField(max_length=30)),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuns.conselhoprofissional')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala_ativa', models.BooleanField(default=True)),
                ('regime_escala', models.CharField(choices=[('P', 'presencial'), ('S', 'sobreaviso')], max_length=2)),
                ('nome_escala', models.CharField(max_length=50, verbose_name='Nome da Escala')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.setor')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
                'ordering': ['nome_escala'],
            },
        ),
        migrations.CreateModel(
            name='EscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala_ativa', models.BooleanField(default=True)),
                ('regime_escala', models.CharField(choices=[('P', 'presencial'), ('S', 'sobreaviso')], max_length=2)),
                ('nome_escala', models.CharField(max_length=50, verbose_name='Nome da Escala')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('escala_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.escala')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuns.periodoreferencia')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.setor')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
                'ordering': ['nome_escala'],
            },
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_plantao', models.DateField(db_index=True)),
                ('indice_plantao_escala', models.IntegerField(blank=True, null=True)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('duracao_plantao', models.DurationField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('plantao_faturado', models.BooleanField(default=False)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.profissional')),
            ],
        ),
    ]
