# Generated by Django 5.0.2 on 2024-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_geral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='regime_escala',
            field=models.CharField(choices=[('P', 'presencial'), ('S', 'sobreaviso')], max_length=10),
        ),
    ]
