# Generated by Django 5.0.3 on 2024-03-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_geral', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantao',
            name='indice_plantao_escala',
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Equipe')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.escala')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeEscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.equipe')),
                ('escala_mensal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_geral.escalamensal')),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_folga', models.DateField(db_index=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.profissional')),
            ],
        ),
    ]
