# Generated by Django 5.0.3 on 2024-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_geral', '0004_horarioplantao_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioplantao',
            name='horario_almoco',
        ),
        migrations.AddField(
            model_name='horarioplantao',
            name='inicio_almoco',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
