# Generated by Django 4.2.7 on 2023-11-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('comuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aditivo', models.IntegerField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tipo_aditivo', models.CharField(choices=[('Aditivo', 'Aditivo'), ('Apostilamento', 'Apostilamento')], default='Aditivo', max_length=50)),
                ('sequencia_aditivo', models.IntegerField()),
                ('aditivo_editavel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'aditivo',
                'verbose_name_plural': 'aditivos',
                'ordering': ['numero_aditivo'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cadastro', 'Cadastro'), ('vigente', 'Vigente'), ('vigente com aditivo', 'Vigente Aditivado'), ('encerrdo', 'Encerrado'), ('rescindido', 'Rescindido')], default='cadastro', max_length=20)),
                ('numero_contrato', models.CharField(max_length=200)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('aditivado', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('motivo_rescisao', models.TextField(blank=True, null=True)),
                ('fornecedor_contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuns.fornecedor')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licitacao', models.CharField(max_length=200)),
                ('objeto', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cadastro_finalizado', models.BooleanField(default=False)),
                ('licitacao_ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'licitação',
                'verbose_name_plural': 'licitações',
            },
        ),
        migrations.CreateModel(
            name='ModalidadeLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modalidade', models.CharField(max_length=30, verbose_name='nome da modalidade')),
                ('modalidade_faturavel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('descricao_lote', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('licitacao_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.licitacao')),
            ],
            options={
                'verbose_name': 'lote da licitação',
                'verbose_name_plural': 'lotes da licitação',
                'ordering': ['numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='LoteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contrato_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('lote_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.lotelicitacao')),
            ],
            options={
                'ordering': ['lote_referencia'],
            },
        ),
        migrations.CreateModel(
            name='LoteAditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditivo_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.aditivocontrato')),
                ('lote_contrato_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.lotecontrato')),
            ],
            options={
                'ordering': ['lote_contrato_referencia'],
            },
        ),
        migrations.AddField(
            model_name='licitacao',
            name='modalidade_licitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.modalidadelicitacao'),
        ),
        migrations.CreateModel(
            name='ItemLoteLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('var_num_item', models.IntegerField(default=0)),
                ('descricao_item', models.CharField(max_length=200)),
                ('informacoes_complementares', models.TextField(blank=True, null=True)),
                ('quantidade_licitada', models.FloatField()),
                ('valor_licitado', models.FloatField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('lote_licitacao_refecencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.lotelicitacao')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ['lote_licitacao_refecencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemLoteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_medida', models.CharField(choices=[('UNID', 'unidade'), ('H', 'hora'), ('D', 'dia')], max_length=15)),
                ('valor_item', models.FloatField()),
                ('quantidade_contratada', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
                ('item_licitacao_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.itemlotelicitacao')),
                ('lote_contrato_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.lotecontrato')),
            ],
            options={
                'verbose_name': 'item do contrato',
                'verbose_name_plural': 'itens do contrato',
                'ordering': ['item_licitacao_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemLoteAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_aditivada', models.FloatField()),
                ('preco_aditivado', models.FloatField()),
                ('item_aditivo_ativo', models.BooleanField(default=True)),
                ('item_contrato_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.itemlotecontrato')),
                ('lote_aditivo_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.loteaditivocontrato')),
            ],
            options={
                'verbose_name': 'item do aditivo',
                'verbose_name_plural': 'itens dos aditivos',
                'ordering': ['item_contrato_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemLicitacaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.itemlotelicitacao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='licitacao_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.licitacao'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='unidade_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.unidade'),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='contrato_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
        ),
    ]
