# Generated by Django 5.0.2 on 2024-02-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlotecontrato',
            name='item_licitacao_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.itemlotelicitacao'),
        ),
        migrations.AlterField(
            model_name='itemlotelicitacao',
            name='unidade_medida',
            field=models.CharField(choices=[('PT', 'posto de trabalho'), ('H', 'hora'), ('P', 'plantao'), ('UNID', 'unidade')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lotecontrato',
            name='lote_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.lotelicitacao'),
        ),
        migrations.CreateModel(
            name='AditivoQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aditivo', models.IntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tipo_aditivo', models.CharField(choices=[('Aditivo', 'Aditivo'), ('Apostilamento', 'Apostilamento')], default='Aditivo', max_length=50)),
                ('aditivo_editavel', models.BooleanField(default=True)),
                ('sequencia_aditivo', models.IntegerField()),
                ('aditivo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.aditivocontrato')),
                ('contrato_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'aditivo de Quantidade',
                'verbose_name_plural': 'aditivos de quantidade',
                'ordering': ['numero_aditivo'],
            },
        ),
        migrations.CreateModel(
            name='QuantidadeAditivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_original', models.FloatField()),
                ('quantidade_aditivada', models.FloatField()),
                ('aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.aditivoquantidade')),
                ('item_aditivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.itemloteaditivo')),
                ('item_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.itemlotecontrato')),
            ],
        ),
    ]
